name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: 'Kustomize Setup'
      uses: imranismail/setup-kustomize@master
      with:
        kustomize-version: "3.1.0"
    - name: "Kustomize build"
      run: kustomize version

