name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: 'Kustomize Setup'
      uses: stefanprodan/kube-tools@v1.2.0
      with:
        kustomize: 3.5.4
        command: |
          kustomize version

