name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: "checkout"
    - name: 'Kustomize Build'
      uses: karancode/kustomize-github-action@master
      with:
        kustomize_version: '3.0.0'
        kustomize_build_dir: 'kustomize/tests/app'
        kustomize_comment: false
        kustomize_build_output: "kustomize/tests/app/rendered.yaml"
